### ISSUE TITLE
Question: Some details about the design choices

### ISSUE THREAD

**Issue by abinoam** [prydonius/spinning_cursor#12]
Hi Adnan,

I'm looking at the problem in my intervals (small chunks of free time).

I would like to be sure about the reasoning behind some of your design choices.
1. Evaluating the action block in the 'outer' context
   - Advantages:
     - You can deal with instance variables of the outer context (as you did in the test)
       should "evalute the block from the calling class"

``` ruby
@num = 1
SpinningCursor.start do
  action do
    @num += 1
   end
end
# Now @num == 2
```
- Disadvantages:
  - You have to explicitly use the SpinningCursor class methods to set the inner state of the cursor

``` ruby
@num = 1
SpinningCursor.start do
  action do
    @num += 1
    SpinningCursor.set_message "New message"
   end
end
```
- Possible workaround
  - We can patch this by passing the parser instance to the action block. So that it could call 'message' directly on the parser instance.

``` ruby
@num = 1
SpinningCursor.start do
  action do |sc| 
    @num += 1
    sc.message "New message"
   end
end
```

2 - Evaluate the block where it is (Parser instance)
- Advantages
  - All the Parser instance methods are available to the action block. So I don't need to do a explicit receiver for calling 'message'
  - The code is simpler and easier to understand and follow. Perhaps less prone to bugs.
  - When lookin to a DSL like yours the user already expect the block is being evaluated under another object binding. So, I think, it's natural not to expect that the outer instance variables be available inside the passed block (IMHO).

``` ruby
@num = 1
SpinningCursor.start do
  action do
    @num += 1
    message "New message"
   end
end
# But @num here is unchaged (==1)
```
- Disadvantages
  - No easy way to access instance variables of the outer scope.

What do you think is the best way?
1) The current way
2) The current way improved with passing the parser instance to a better interface
3) The new way evaluating the action block inside the Parser instance.

Why?

**Comment by abinoam** [comment]
I prefer the number 3 but you're the BOSS!

**Comment by abinoam** [comment]
Another pattern that I've just thought is to add a **'setup'** method that accepts a block but no an action block inside it.

So that we could do this

``` ruby
@num = 1
sc = SpinningCursor.setup do
  banner "My banner"
  type :spinner
  delay 0.5
end

sc.start
@num += 1
sc.stop

# Now @num == 2 and the code make it clear that the @num instance variables are the same.
```

It also can be...

``` ruby
@num = 1
SpinningCursor.setup do
  banner "My banner"
  type :spinner
  delay 0.5
end

SpinningCursor.start
@num += 1
SpinningCursor.stop
```

And, instead of naming **'start'** we could name it **'run'** so that it makes clear the differences between run and setup. Where **run** starts the cursor and stops it at the end of the action. And **setup** just _setup_ things without starting or stoping any action.

``` ruby
SpinningCursor.run do
  banner "My banner"
  type :spinner
  delay 0.5
  action do
    do_something
  end
end
```

**Comment by prydonius** [comment]
I like the run and setup features you proposed. Go ahead and make a separate bug for
them, however due to backwards compatibility the milestone will be set to
1.0.0 rather than 0.2.0.

As for the evaluation context of the action block, well I would like it to
tie in with the calling context as it makes sense that people may want to
use instance variables and methods (even though from the parser context the
method_missing can be used to drop back to originator methods). So yielding
the parser context to the block, although not as clean, is better in my
opinion. Either that or we can figure out some way of getting instance
variables from the originator class when they are missing, there's probably
a metaprogramming way of doing this like method_missing.

I will set the milestone of this bug to 1.0.0 too.

Once I pull in your changes from bug #11 and have bug #7 completely done with
it's options I'll release 0.2.0. Then 1.0.0 can come after that.

Unfortunately I don't have much time to do this during the weekdays, I have
a very busy work schedule for a few weeks! I will hopefully be able to
release 0.2.0 this weekend if not earlier.

Again I have to say thank you, and I really appreciate all the effort
you're putting into this little gem. I stopped working on it for a year and
your effort has also made me want to contribute to it more, so thank you :).

**Comment by abinoam** [comment]
Having some free time now.
Working on it.
Today or tomorrow I'll push the code.

Abinoam Jr.

On Tue, Jul 2, 2013 at 6:31 PM, Adnan Abdulhussein <notifications@github.com

> wrote:
> 
> I like the run and setup features you proposed. Go ahead and make a bug
> for
> them, however due to backwards compatibility the milestone will be set to
> 1.0.0 rather than 0.2.0.
> 
> As for the evaluation context of the action block, well I would like it to
> tie in with the calling context as it makes sense that people may want to
> use instance variables and methods (even though from the parser context
> the
> method_missing can be used to drop back to originator methods). So
> yielding
> the parser context to the block, although not as clean, is better in my
> opinion. Either that or we can figure out some way of getting instance
> variables from the originator class when they are missing, there's
> probably
> a metaprogramming way of doing this like method_missing.
> 
> Please make a bug about this as well, it will be something we can push out
> in 1.0.0.
> 
> Once I pull in your changes from bug 11 and have bug 7 completely done
> with
> it's options I'll release 0.2.0. Then 1.0.0 can come after that.
> 
> Unfortunately I don't have much time to do this during the weekdays, I
> have
> a very busy work schedule for a few weeks! I will hopefully be able to
> release 0.2.0 this weekend if not earlier.
> 
> Again I have to say thank you, and I really appreciate all the effort
> you're putting into this little gem. I stopped working on it for a year
> and
> your effort has also made me want to contribute to it more, so thank you
> :).
>

**Comment by prydonius** [comment]
Separated into its own issue. Please raise a new issue if you want to reconsider the evaluation of the action block.

**Comment by prydonius** [comment]
Reopening as I'm interested to see what we can do about the evaluation context. Having a look at this SO post[1], we could cheat to make instance variables fall back to the outer context just like normal methods do.

Also, the only block that's being evaluated in the parser context is the block passed to SpinningCursor#start, so I'm a little confused as to why there is a method missing in parser in the first place, this would allow things like:

``` ruby
def my_awesome_method
  puts 'hehe'
end

SpinningCursor.start do
  message "blah"
  action do
    sleep 10
  end
  my_awesome_method
end
```

Which would result in 'hehe' being printed before the cursor starts. This is incorrect and should not be allowed. However, after attempting to remove the method_missing method I'm still being able to evaluate that method. Any ideas why?

[1] http://stackoverflow.com/questions/7671493/is-there-a-way-to-override-instance-variable-lookup-at-ruby/7671694#7671694

**Comment by prydonius** [comment]
Ah, it's explained here:
http://stackoverflow.com/questions/156394/method-access-in-ruby

In that case there is nothing much we can do to prevent that (however at the moment it would be calling methods attached to classes as well i.e. the above snippet would work even if it was wrapped in a class). I guess we can just ignore that.

**Comment by abinoam** [comment]
Close this issue.
The **my_awesome_method** is being defined on Object.
So it's on the chain to be called.
As explained on the SO link.

**Comment by prydonius** [comment]
There is still the issue of the evaluation context.

> What do you think is the best way?
> 1) The current way
> 2) The current way improved with passing the parser instance to a better interface
> 3) The new way evaluating the action block inside the Parser instance.

As I said earlier, I agree that typing `SpinningCursor` is a nuisance, I like number 2 in that it's a quick fix, although it's not very DSL-friendly. The third option concerns me, what if I have a method in my class that is of the same name as one in `SpinningCursor::Parser`?

E.g.

``` ruby
def message(arg)
  puts arg
end

SpinningCursor.start do
  message "busy"
  action do
   sleep 2
   message "gah"
   sleep 2
  end
end
```

Currently this works, if we implement option 3, it will break. It's quite unlikely, but you never know. It's also not a massive problem since the user can just rename their method, but it may be annoying.

**Comment by prydonius** [comment]
Woops, I guess #24 closes this!
