### ISSUE TITLE
Support colorisation of messages/banners

### ISSUE THREAD

**Issue by shreyasbharath** [prydonius/spinning_cursor#3]
As title states, it'd be really cool if Spinning Cursor supported colorisation of console messages (in a platform independent way - should work on Linux, Windows, Mac etc.).

**Comment by prydonius** [comment]
Hey,

Since banners and messages are just strings you can encode the colours in ANSI in the string. You can also use this gem https://rubygems.org/gems/colorize which makes it easier. i.e.

``` ruby
SpinningCursor.start do
    action { sleep 10 }
    banner "An amazing task is happening".blue
    message "Failed".red
end
```

Although in the output, only "An amazing task is happening" will be blue, the cursor will not be coloured. I'd have to bundle colorize with spinning cursor to provide this, but I'm not sure it's really needed.

**Comment by shreyasbharath** [comment]
Thank you for replying back.

I am actually using your gem to show progress of a series of actions to the user. These actions can either succeed or fail and colour seems to be the best way to highlight success/failure to the user.

I ended up using the Windows Console API to set the colour manually, but it'd be nice and convenient if this was part of the gem itself.

**Comment by prydonius** [comment]
Is there any reason why you've chosen Windows Console API over ANSI encoding/colorize gem? Does colorize work on Windows? If I were to make this part of the gem colorize seems like the easiest option to me.

**Comment by shreyasbharath** [comment]
The Windows Console does not support ANSI encoding so you need a translation layer that converts the ANSI codes to Windows Console attributes. 

I tried [term-ansicolor](https://github.com/flori/term-ansicolor) in combination with [win32console](https://github.com/luislavena/win32console) but I ran into a few bugs. I haven't tried colorize but it relies on win32console too.

**Comment by prydonius** [comment]
Hmm could you try out colorize for me? If that doesn't work, how are you using the Windows Console API, so that I can replicate it in spinning cursor?

**Comment by shreyasbharath** [comment]
I am using it like so to set the console colour -

```
def set_console_colour(colour)
  get_std_handle = Win32API.new("kernel32", "GetStdHandle", ['L'], 'L')
  set_console_txt_attrb =
  Win32API.new("kernel32", "SetConsoleTextAttribute", ['L','N'], 'I')
  hout = get_std_handle.call(-11)

  if colour == :red
    set_console_txt_attrb.call(hout, 12)
  elsif colour == :green
    set_console_txt_attrb.call(hout, 2)
  else
    set_console_txt_attrb.call(hout, 7)
  end
end

SpinningCursor.start do
  type :dots

  banner "blah blah"
  action do
    set_console_colour(:green)
    SpinningCursor.set_message("bleh")
  end
end
```

I will try out colorize and let you know how I go.

**Comment by prydonius** [comment]
I tried colorize on windows a while ago and ANSI colour codes don't work, I'm afraid.

Since it's a cross-platform issue I'm going to say it's not something `spinning_cursor` needs to solve. I'd like to keep it simple with as little dependencies as possible, it was never intended to be a fully featured mega library ;).

Closing with wontfix. Feel free to reopen if you disagree.
