### ISSUE TITLE
Return statements in action block causes explosions :(

### ISSUE THREAD

**Issue by prydonius** [prydonius/spinning_cursor#6]
e.g.

``` ruby
SpinningCursor.start do
  action do
    sleep 2
    return "bananas"
  end
  message "are good"
end
```

Causes 'unexpected return' error.

**Comment by abinoam** [comment]
Forget the "return". ;-)
You will need it rarely and most to make the code clearer.

Do this

``` ruby
SpinningCursor.start do
  action do
    sleep 2
    "bananas"
  end
  message "are good"
end
```

Not a bug.
You can't "return" within a block being instance_evaluated.
Test

"a".instance_eval { self.upcase }
"a".instance_eval { return self.upcase }

We can try to bypass this. 

I'll take a look further.

**Comment by prydonius** [comment]
Did you manage to find a way around this, or should we close it and mark it 'wontfix' as it's stupid to use a return statement there anyway?

**Comment by abinoam** [comment]
Well... I've done a tiny search over here and...
Some people NEED to workaround this... (2007) http://blog.jayfields.com/2007/03/ruby-localjumperror-workaround.html 
Some other people just assume that shouldn't be any "return" inside blocks that are being instance evaluated.
https://github.com/capistrano/capistrano/commit/1d392aa (capistrano is a respectful code base)
Here we can even see it on tests as the defaul behaviour of a Ruby implementation...

``` ruby

begin
  "".instance_eval 'return'
rescue LocalJumpError => e
  test_ok(e.message =~ /unexpected return$/)
end
```

Source: 
1) http://svn.codehaus.org/jruby/branches/rbx/test/testEval.rb
2) http://rxr.whitequark.org/jruby/source/test/testEval.rb?v=1.6.7.2

Here at stackoverflow we have a short differantiation of the 3 kinds of "return" statements

**_return**_ always returns from method, but if you test this snippet in irb you don't have method, that's why you have LocalJumpError
**_break**_ returns value from block and ends its call. If your block was called by yield or .call, then break breaks from this iterator too
**_next**_ returns value from block and ends its call. If your block was called by yield or .call, then next returns value to line where yield was called
Source: http://stackoverflow.com/questions/2325471/using-return-in-a-ruby-block

This other stackoverflow question helps further...
http://stackoverflow.com/questions/626/when-to-use-lambda-when-to-use-proc-new

So... If you really think "return" is important, we have to try any of the possible workarounds.
But... I wouldn't care about it. As it's the default behaviour.
Anything different will be "suprising".
And... if some issue raises in the future, we can always workaround it.

**Comment by prydonius** [comment]
Yeah, if it's the default then no point in working around it, since it's obviously not the right way of doing things. However, in this case I think the current behaviour of evaluating the action in the originator context is good since that allows to set variables during the run of the cursor and use them afterwards (there could be a way around this, i.e. having a method that 'stashes' variables in a hash, but the current way is cleaner in my opinion).

Marking closed, wontfix.
